#+title: Parallel Computation of the Tutte Polynomial
#+subtitle: 15-418: Project #71
#+author: Akira Kyle
#+date: April 18, 2018
#+email: akyle@cmu.edu
#+options: toc:nil email:t
#+latex_header_extra: \pagestyle{fancy}
#+latex_header_extra: \fancyhead[R]{Akira Kyle}
#+latex_header_extra: \fancyhead[L]{15-418}
#+latex_header_extra: \fancyhead[C]{Parallel Computation of the Tutte Polynomial}
#+latex_header_extra: \fancyfoot[C]{\thepage}

* Links
** Tutte background
[[https://en.wikipedia.org/wiki/Tutte_polynomial]]
Brendan McKay Nauty and Traces [[http://pallini.di.uniroma1.it/]]
Haggard C++ tuttepoly code [[http://homepages.ecs.vuw.ac.nz/~djp/tutte/]]
Mathematica tutte polynomial function [[http://reference.wolfram.com/language/ref/TuttePolynomial.html]]
Monagan maple tutte polynomial code [[http://www.cecm.sfu.ca/~mmonagan/tutte/]]
Vertex-exponential time tutte polynomial [[https://github.com/thorehusfeldt/tutte_bhkk]]
Blog post using tutte_bhkk in python [[http://mhenderson.net/page3/]]
** Five-flow
https://symomega.wordpress.com/2010/06/13/roots-of-flow-polynomials-and-welshs-conjecture/

** Fortran
http://www.featflow.de/en/software/featflow2/tutorial/tutorial_lang.html
https://en.wikibooks.org/wiki/Fortran
http://www.cs.rpi.edu/~szymansk/OOF90/bugs.html
http://kitchingroup.cheme.cmu.edu/blog/2014/02/04/Literate-programming-example-with-Fortran-and-org-mode/


* Project proposal
** Summary
 I will implement and optimize an algorithm to compute the Tutte Polynomial for
 arbitrary graphs using both MPI and openMP. I will examine the effect of
 different edge selection heuristics on the performance scaling of the program. 

** Background
 In the search for a proof to the four color theorem, the mathematician George
 David Birkhoff came up with the Chromatic Polynomial which counts the number of
 possible colorings of a graph as a function of $k$ possible colors to color it
 with. If one can show that this polynomial is positive for all planar graphs
 when $k=4$, then one proves the four color theorem. While it didn't prove useful
 in actually proving the four color theorem, W.T. Tutte generalized this
 chromatic polynomial to the Tutte Polynomial which has become an important Graph
 invariant that has been related to results from knot theory, combinatorics, and
 statistical physics. 

 The Tutte Polynomial can be defined recursively using edge contraction ($G/e$)
 and edge deletion ($G - e$) on an undirected graph $G$ as

 \[T_G(x,y) = T_{G-e}(x,y) + T_{G/e}(x,y)\]

 where $e$ must be neither a bridge nor a loop. The base case being when $G$
 contains only $i$ bridges and $j$ loops is $T_G(x,y) = x^iy^j$

 The Tutte polynomial can also be given in closed form for a graph $G = (V, E)$
 by:

 \[T_G(x,y) = \sum_A\subseteq E (x-1)^{k(A) - k(E)}(y-1)^{k(A) + |A| - |V|}\] 

 Where $k(A)$ is the number of connected components of $(V,A)$. 

 From this statement of the Tutte polynomial one can guess that it happens to #P
 hard, as the sum is over the power set of the edges. Evaluating the it a various
 points yields various results of interest, for example $y=0$ gives the chromatic
 polynomial. The Wikipedia page has a good summary of this discussion
 ([[https://en.wikipedia.org/wiki/Tutte_polynomial]]).

** The Challenge

 Between the two definitions given above, the recursive definition is the most
 promising for implementing a fast algorithm. This is because it naturally
 creates a computation tree with potentially redundant computation being
 performed along some branches which we can use Dynamic Programming ideas to
 speedup. The following illustration (taken from the wikipedia article)
 illustrates an example of calculating the Tutte polynomial using the recursive
 deletion-contraction definition.

 #+attr_latex: :width 4in
 [[file:figs/Deletion-contraction.svg]]

 To find branches with redundant computation we need to be able to identify
 isomorphic graphs. One of the most prominent programs for doing so is the nauty
 and Traces program written by Brendan McKay ([[http://pallini.di.uniroma1.it/]]).
 This program can output a canonical labeling for a graph which can then be used
 as a key in a graph cache.

 The interesting issues to consider in paralleling this will be surrounding this
 cache as it is the central part to speeding up this otherwise intractable
 computation. Sharing this cache safely and efficiently across all the processes
 in MPI may be difficult and might benefit from compressing the graphs. Also
 locking the cache data structure within a process in openMP when it needs to be
 updated will be tricky to keep the overhead low.

 Furthermore while each of the two recursive calls can be done in parallel, it is
 not guaranteed that each will have an equal division of work, especially if one
 side ends up having more cache hits than the other, so scheduling will be
 another issue that will likely have to be done dynamically, potentially with
 some type of work queue. Hiding latency can be a potential area for speedups
 since finding the graph isomorphisms is a relatively compute intensive process
 while the cache lookup and additions are a memory intensive process. Finally the
 usual

** Resources
 /Computing Tutte Polynomials/ by Gary Haggard, David J. Pearce, and Gordon Royle
 (2010) will probably be the basis of my implementation as they seem to have the
 ``current'' best implementation. Their code is available on David Pearce’s web-
 site at [[http://homepages.ecs.vuw.ac.nz/~djp/tutte/]] and is implemented in C++.
 This will serve as my reference to check against for both correctness and
 sequential performance, however I will likely rewrite this from scratch in
 fortran (since I'll be spending my summer internship in fortran so I'd like to
 get some practice) to ensure I understand the algorithm completely (it's not a
 very substantial amount of code). Like their implementation, I will use Brendan
 McKay's nauty for finding graph isomorphisms.

 I may also checkout Mathematica's function to compute the Tutte polynomial as
 another benchmark to compare to
 ([[http://reference.wolfram.com/language/ref/TuttePolynomial.html]]).

 Furthermore a more recent paper /A new edge selection heuristic for computing
 the Tutte polynomial of an undirected graph./ by Michael Monagan (2018) proposes
 a different heuristic from those of Haggard, Pearce, Royale that Monagan claims
 offers massive speedups on many types of graphs. His implementation is in Maple
 and is available at [[http://www.cecm.sfu.ca/~mmonagan/tutte/]].

 Finally an older paper /Computing the Tutte Polynomial in Vertex-Exponential
 Time/ by Andreas Björklund, Thore Husfeldt, Petteri Kaski, Mikko Koivisto (2008)
 which is referenced by Haggard, Pearce, Royle has code available here
 [[https://github.com/thorehusfeldt/tutte_bhkk]] along with a nice blog post
 using it here [[http://mhenderson.net/page3/]].

 I think between the latedays cluster and the ghc machines, I will be sufficient
 hardware to perform scaling experiments and performance assessments.

** Goals and Deliverables
*** Plan to achieve
 - A complete working program using MPI capable of correctly computing Tutte
   polynomials at speeds comparable to the reference implementations and with
   good performance scaling .
 - The three edge selection heuristics (2 from Haggard, Pearce, Royle, 1 from
   Monagan) implemented and a comparison of their performance scaling.

*** Hope to achieve
 - Verifying the result listed of Pearce's website of the Tutte polynomial of the
   Truncated Icosahedron.

 Haggard, Pearce, Royle claim it took one week on 150 machines to calculate,
 however Monagan claims it took four minutes on a single cpu using his edge
 selection heuristic. I would like to be able to meet and exceed both of these
 benchmarks for performance however its difficult to specify a speedup since
 Pearce doesn't list the machine specs used, however given this was achieved in
 2009, I expect the specs on the latedays cluster to be much better. As for the
 Monagan result, since he implemented this in Mapel using no isomorphism test, I
 would hope to get at least a 2x speedup (conservative) due to not having the
 overhead of the maple runtime and additional speedup of from additional pruning
 the computation tree due to isomorphisms.

 - An openMP implementation to compare with the MPI implementation.
 - A combined MPI and openMP implementation to compare to the individual
   implementations.

** Platform Choice
 I will use fortran (since I'll be spending my summer internship in fortran so
 I'd like to get some practice) and MPI and openMP and run on the latedays
 cluster and ghc machines. For this type of application MPI is the most important
 to utilize since to have hope to scale to really massive graphs exceeding what
 can be held in memory by a single machine, it is necessary to use a distributed
 model.

** Schedule
 - Week of April 16th
   - Test harness and sequential implementation
   - Understanding of nauty canonical labeling format and code to interface with
     it (necessary for graph cache)
 - Week of April 23rd
   - Parallel MPI implementation with graph cache and Haggard, Pearce, Royle
     heuristics 
 - Week of April 30th
   - Parallel OpenMP implementation with Monagan heuristic.


* Nauty info

#+begin_example
$ ./nautest 
NAUTYVERSION=2.6 (64 bits)  NAUTYVERSIONID=26040  HAVE_TLS=0
MAXN=0  MAXM=0  WORDSIZE=64  NAUTY_INFINITY=2000000002
sizes: short=2 int=4 long=8 double=8 boolean=4 setword=8
CLZ=1,1,1  POPCNT=1,1,1;0,0
LONG_LONG_COUNTERS=0  COUNTER_FMT=%lu
defined: __STDC__ SETWORD_LONG
DOPROMPT(stdin)=1 DOPROMPT(stdout)=1
CPUTIME = 0.000000
INITSEED: seed=416931912
#+end_example


* Code
** .gitignore
#+begin_src .gitignore :tangle .gitignore
# Ignore everything
*
# except this literate org file
!paralleltuttepoly.org
#+end_src

** Makefile
#+begin_src makefile :tangle Makefile
# nauty/nauty.a:
# 	$(MAKE) -C nauty nauty.a
# tutte: tutte.c nauty/nauty.h nauty/nauty.a
# 	gcc -o tutte tutte.c nauty/nauty.a -Inauty

tutte: tutte.c nauty/nausparse.h nauty/nausparse.c
	gcc -o tutte tutte.c nauty/nausparse.c -Inauty

execute: tutte
	./tutte test.g6

clean:
	$(MAKE) -C nauty clean
	rm -f tutte *.o
#+end_src

** tests
#+begin_src bash :results raw drawer
gsed -e 's/,/\n/g' -e 's/--/:/g' -e '1i\n=10 g' -e '$a\.' edge10 | nauty/dretog > test.g6
cat test.g6
#gsed -e 's/,/\n/g' -e 's/--/:/g' -e '1i\n=10 g' -e '$a\.\nt' edge10 | nauty/dreadnaut
#+end_src

#+RESULTS:
:RESULTS:
I|eMID@WG
:END:

** includes
#+name: includes
#+begin_src c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

 /* MAXN=0 is defined by nauty.h, which implies dynamic allocation */
#include "nauty.h"
#include "gtools.h"
#include "gutils.h"
#+end_src

** macros
#+name: macros
#+begin_src c
#define USAGE "Usage: tutte [-h] [-q] [-p#] [infile [outfile]]\n"

#define HELPTEXT \
" Computes the Tutte polynomial of a graph.\n\
\n\
    infile  the input graph file in either graph6 or sparse6 format.\n\
\n\
    outfile  the output file for the computed polynomial.\n\
\n\
    -p#  choose the which graph in the input file.\n\
         The first graph is number 1. (default 1)\n\
    -v  be verbose\n\
    -h  show this help text\n"

#define HASH_KEY 1

#define print(...) if (verbose) printf(__VA_ARGS__)

#define SWAP(x, y, T) do { T SWAP = x; x = y; y = SWAP; } while (0)
#define MAX(x, y) (((x) > (y)) ? (x) : (y))
#define MIN(x, y) (((x) < (y)) ? (x) : (y))

#define NOT_CONNECTED 0x00

#define MG_VDEM(mgp,vv,dd,ee,mm) do { \
vv = ((sparsegraph*)(mgp))->g->v; \
dd = ((sparsegraph*)(mgp))->g->d; \
ee = ((sparsegraph*)(mgp))->g->e; \
mm = ((sparsegraph*)(mgp))->mult; \
} while(0)

int verbose = 0;

#define SAFE_ALLOC
#ifdef SAFE_ALLOC
#define alloc(...) safe_alloc(__VA_ARGS__)
void *
safe_alloc(size_t n)
{
  void *p = malloc(n);
  if (p == NULL) {fprintf(stderr, "error in malloc"); exit(1);}
  return p;
}
#else
#define alloc(...) malloc(__VA_ARGS__)
#endif

#define increase_ratio 1.5
#+end_src

** graph data structure
#+name: graphs
#+begin_src c
typedef struct mgraph
{ // an undirected multigraph
  int *d;      /* Array with degree of each vertex */
  int *e;      /* Array to hold lists of neighbours */
  int *mult; // multiplicity of "virtual mulitedge" vertex, 0 if normal vertex
  int *free; // indices of disconnected vertices
  int nv;      /* Number of vertices */
  size_t nde;  /* 2 * Number of edges */
  int nfree; // number of free vertices
  size_t vlen,dlen,elen,multlen,freelen;  /* Sizes of arrays in units of type */
} mgraph;

mgraph *
new_mgraph(int nv, int nde)
{
  int nvt = nv*increase_ratio
  mgraph *g = (mgraph *)alloc(sizeof(mgraph));
  g->nv = nv;
  g->nde = nde;
  g->nfree = nvt - nv;
  g->dlen = nvt;
  g->elen = nvt*nvt;
  g->multilen = nvt;
  g->freelen = nvt;
  g->d = (int *)alloc(sg->dlen * sizeof(int));
  g->e = (int *)alloc(sg->elen * sizeof(int));
  g->mult = (int *)alloc(sg->multlen, sizeof(int));
  g->free = (int *)alloc(sg->freelen, sizeof(int));
  return g;
}

#define nbr(g, u, i) g->e[i + u * g->dlen]

mgraph *
sparsegraph_to_mgraph(sparsegraph *sg)
{
  mgraph *g = new_mgraph(sg->nv, sg->nde);
  for (int i = 0; i < sg->nv; i++)
    {
      g->d[i] = sg->d[i];
      for (int j = 0; j < sg->d[i]; j++)
        nbr(g,i,j) = sg->e[v[]]

    }
  
  g->g = sg;
  g->mult = (int *)calloc(sg->nv, sizeof(int));
  return g;
}

mgraph *
new_mgraph_from_mgraph(mgraph *og, int nv, int nde)
{ //nv > g->g->nv and nde > g->g->nde
  SG_DECL(sg);
  SG_ALLOC(sg, nv, nde, "malloc sg");

  mgraph *g = (mgraph *)malloc(sizeof(mgraph));
  copy_sg(og->g, sg);
  g->g = sg;
  g->mult = (int *)malloc(nv * sizeof(int));
  memcpy(g->mult, og->mult, nv * sizeof(int));
  return g;
}

void
free_mgraph(mgraph *g)
{
  free(g->mult);
  SG_FREE(g->g);
  free(g);
}

typedef struct edge
{
  int a;
  int b;
  int virt;
} edge;


edge
to_edge(mgraph *g, int a, int b)
{
  MG_VDEM(g,v,d,e,m);
  if (!(m[a]) && !(m[a])) return (edge){ .a = a, .b = b, .virt = -1};
  if (!(m[a]))
    {
    int c = (e[v[b]] == a) ? e[v[a]+1] : e[v[b]];
    return (edge){ .a = a, .b = c, .virt = b};
    }
  if (!(m[b]))
    {
    int c = (e[v[a]] == b) ? e[v[b]+1] : e[v[a]];
    return (edge){ .a = c, .b = b, .virt = a};
    }
  fprintf(stderr, "invalid pair passed to_edge\n");
}

typedef struct mgraph_info
{
  int props;
  mgraph **comps;
  int comps_len;
} mgraph_info;

void
free_mgraph_info(mgraph_info *info)
{
  for (int i = 0; i < info->comps_len; i++)
    free_mgraph(info->comps[i]);
  free(info->comps);
  free(info);
}
#+end_src

** polynomial data structure
#+name: polys
#+begin_src c
typedef struct poly
{ // a polynomial
  long *c;
  int y_deg;
  int x_deg;
} poly;

poly *
new_poly(x_deg, y_deg)
{
  poly *p = (poly *)calloc(1, sizeof(poly));
  p->c = (long *)calloc((x_deg+1)*(y_deg+1), sizeof(long));
  p->x_deg = x_deg;
  p->y_deg = y_deg;
  return p;
}

void
free_poly(poly *p)
{
  free(p->c);
  free(p);
}

long *
poly_coeff(poly *A, int x, int y)
{
  if (x > A->x_deg) return 0;
  if (y > A->y_deg) return 0;
  return &A->c[y + x*A->y_deg];
}

void
print_poly(FILE *fout, poly *p)
{
  for (int x = 0; x <= p->x_deg; x++)
    for (int y = 0; y <= p->y_deg; y++)
      fprintf(fout, "%ldx^%dy^%d\n", *poly_coeff(p, x, y), x, y);
}

poly *
poly_add(poly *A, poly *B)
{
  poly *C = new_poly(MAX(A->x_deg, B->x_deg), MAX(A->y_deg, B->y_deg));
  for (int x = 0; x <= C->x_deg; x++)
    for (int y = 0; y <= C->y_deg; y++)
      ,*poly_coeff(C, x, y) = *poly_coeff(A, x, y) + *poly_coeff(B, x, y);
  free_poly(A); free_poly(B);
  return C;
}

poly *
poly_mult(poly *A, poly *B)
{
  poly *C = new_poly((A->x_deg + B->x_deg), (A->y_deg + B->y_deg));

  for (int ax = 0; ax <= A->x_deg; ax++)
    for (int ay = 0; ay <= A->y_deg; ay++)
      for (int bx = 0; bx <= B->x_deg; bx++)
        for (int by = 0; by <= B->y_deg; by++)
          ,*poly_coeff(C, ax+bx, ay+by) = ( (*poly_coeff(A, ax, ay)) *
                                           (*poly_coeff(B, bx, by)) );
  free_poly(A); free_poly(B);
  return C;
}
#+end_src

** tarjan graph search
#+name: tarjan
#+begin_src c
/*
  poly * tutte(mgraph *g);

  mgraph_info *
  search_mgraph(mgraph *g)
  {


  }
,*/

int
bridge_helper(mgraph *g, int a, int c)
{
  MG_VDEM(g,v,d,e,m);
  if (a == c) return 1;
  else
    for (int i = 0; i < d[c]; i++)
      if bridge_helper(g, u, e[v[c] + i]) return 1;
  return 0;
}

int
is_bridge(mgraph *g, int a, int b)
{
  MG_VDEM(g,v,d,e,m);
  for (int i = 0; i < d[a]; i++)
    if (i != b) 
      if (bridge_helper(g, a, e[v[c] + i])) return 0;
  return 1;
}


#+end_src

** reductions
#+name: reductions
#+begin_src c

boolean
edge_is_loop(mgraph *g, edge e)
{
  if (e.u == e.v) return TRUE; //assert(e.virt == 1)
  return FALSE;
}

boolean
edge_is_bridge(mgraph *g, edge e)
{
  if (e.virt >= 0) return FALSE;
  return is_bridge(g, e.u, e.v);
}

edge select_edge(mgraph *g) 
{
  MG_VDEM(g, v, d, e, m);
  for (int i = 0; i < g->g->nv; i++)
    if (!m[i] && (d[i] > 0))
      return to_edge(i, e[v[i]])

  fprintf(stderr, "select_edge called on empty graph\n");
  return (edge){ .u = -1, .v = -1 };
}

mgraph *
delete_arc(mgraph *g, int u, int v)
{
  MG_VDEM(g, v, d, e, m);
  int delete_flag = 0;
  for (int i = 0; i < d[e.a]; i++)
    {
      if (e[v[e.a]+i] == e.b) delete_flag = 1;
      if (delete_flag && i != d[e.a]) 
        e[v[e.b]+i] = e[v[e.a]+i+1];
    }
  d[e.a]--; d[e.b]--;
}

mgraph *
delete_edge(mgraph *g, edge e)
{
  if (e.a == e.a)
    {
      delete_arc(g, e.a, e.virt); delete_arc(g, e.virt, e.a);
      return g;
    }
  if (e.virt >= 0)
    {
      delete_arc(g, e.a, e.virt); delete_arc(g, e.virt, e.a);
      delete_arc(g, e.b, e.virt); delete_arc(g, e.virt, e.b);
      return g;
    }

  delete_arc(g, e.a, e.b); delete_arc(g, e.b, e.a);
}

void
neighbor_intersection(mgraph *g, e);
{
  
}

mgraph *
contract_edge(mgraph *g_in, edge ab)
{ // assume no loops
  MG_VDEM(gi, vi, di, ei, mi);

  new_virt_verts = 0;
  for (int i = 0; i < di[ab.a]; i++)
    for (int j = 0; j < di[ab.b]; j++)
      if (ei[vi[ab.a]+i] == ei[vi[ab.b]+j]) new_virt_verts++;

  mgraph *g = new_mgraph_from_mgraph(g_in,
                                     g_in->g->nv + new_virt_verts,
                                     g_in->g->nde + di[ab.a] + di[ab.b]);
  size_t va_new = g_in->elen;
  free_mgraph(g_in);

  MG_VDEM(g, v, d, e, m);

  for (int i = 0; i < d[ab.a]; i++) e[va_new+i] = e[v[ab.a]+i];
  v[ab.a] = va_new;

  for (int j = 0; j < d[ab.b]; j++)
    {
      edge aj;
      edge bj;
      delete_edge(g, bj);
      add_edge(g, aj);
/*
      if (is_triangle(e, j, &aj, &bj));
        {
          delete_edge(g, bj);
          add_edge(g, aj);
        }
      else
        {
          e[v[ab.a]+d[ab.a]] = e[v[ab.b]+j];
          d[ab.a]++;
        }
*/
    }
  return g;
}

poly *
reduce_components(mgraph *g, mgraph_info *info)
{
  // assert(info->comps_len > 1)
  poly *p = tutte(info->comps[0]);
  for (int i = 1; i < info->comps_len; i++)
    p = poly_mult(p, tutte(info->comps[i]));
  return p;
}

poly *
reduce_trees(mgraph *g, mgraph_info *info)
{
  return NULL;
}

poly *
reduce_multiears(mgraph *g, mgraph_info *info)
{
  return NULL;
}
poly *
reduce_loops(mgraph *g, mgraph_info *info)
{
  return NULL;
}
poly *
reduce_multiedges(mgraph *g, mgraph_info *info)
{
  return NULL;
}

poly *
reduce_edge_heuristic(mgraph *g, mgraph_info *info)
{
  edge e = select_edge(g);
  poly *pd = tutte(delete_edge(g, e));
  poly *pc = tutte(contract_edge(g, e));
  return poly_add(pc, pd);
}


#+end_src

** tutte
#+name: tutte
#+begin_src c
poly *
tutte(mgraph *g)
{

  // if hashgraph(g) in cache: return cache[key]
  //fcanonise(g, m, n, h, NULL, FALSE);
  //long hash = hashgraph(g, m, n, HASH_KEY);
  //char* graph_str = ntog6(g, m, n);
  //printf("%s->%ld\n\n", graph_strg, hashg);
  //else

  poly *p;
  /*
  mgraph_info *info = search_mgraph(g);

  if      (info->props & NOT_CONNECTED) p = reduce_components(g, info);
  else if (info->props & NOT_CONNECTED) p = reduce_trees(g, info);
  else if (info->props & NOT_CONNECTED) p = reduce_multiears(g, info);
  else if (info->props & NOT_CONNECTED) p = reduce_loops(g, info);
  else if (info->props & NOT_CONNECTED) p = reduce_multiedges(g, info);
  else                                  p = reduce_edge_heuristic(g, info);

  // cache[hashgraph(g)] = p
  free_mgraph_info(info);
  ,*/
  if (g->g->nde == 0) 
    {
      p = new_poly(0,0);
      ,*poly_coeff(p, 0, 0) = 1;
      free_mgraph(g);
    }
  else
    {
      edge e = select_edge(g);
      if (edge_is_loop(g, e))
        {
          p = tutte(delete_edge(g, e));
          poly *y = new_poly(1,0);
          ,*poly_coeff(y, 0, 0) = 0; *poly_coeff(y, 1, 0) = 1;
          p = poly_mult(p, y);
        }
      else if (edge_is_bridge(g, e))
        {
          p = tutte(contract_edge(g, e));
          poly *x = new_poly(1,0);
          ,*poly_coeff(x, 0, 0) = 0; *poly_coeff(x, 1, 0) = 1;
          p = poly_mult(p, x);
        }
      else {
        mgraph *gc = copy_mg(g)
        poly *pd = tutte(delete_edge(g, e));
        poly *pc = tutte(contract_edge(gc, e));
        p = poly_add(pc, pd);
      }
    }

  return p;
}
#+end_src

** main
#+name: main
#+begin_src c
int
main(int argc, char *argv[])
{
  char* infile = NULL;
  char* outfile = NULL;
  FILE* fin = NULL;
  FILE* fout = NULL;
  int n,m;
  int codetype;
  boolean digraph;

  int c;
  long position = 1;

  while ((c = getopt (argc, argv, "hvp:")) != -1)
    switch (c)
      {
      case 'h':
        printf("%s\n%s", USAGE, HELPTEXT);
        return 0;
      case 'q':
        verbose = 1;
        break;
      case 'p':
        position = strtol(optarg,(char **)NULL, 10);
        break;
      case '?':
        printf("%s", USAGE);
        return 1;
      default:
        abort ();
      }
  if (optind < (argc-2))
    {
      fprintf(stderr, "Too many non-option arguments\nUse tutte -h for help\n%s", USAGE);
      return 1;
    }
  if (optind == (argc-2)) {infile = argv[optind]; outfile = argv[optind+1];}
  if (optind == (argc-1)) infile = argv[optind];

  fin = opengraphfile(infile, &codetype, 0, position);
  if (fin == NULL)
    {fprintf(stderr, "error opening file", USAGE); exit(1);}
  sparsegraph *sg = read_sg(fin, NULL);
  n = sg->nv; m = SETWORDSNEEDED(n);
  nauty_check(WORDSIZE,m,n,NAUTYVERSIONID);
  print("n = %d, m = %d\n", n, m);
  put_sg(stdout, sg, FALSE, 80);

  mgraph *mg = sparsegraph_to_mgraph(sg)
  poly *p = tutte(mg);

  if (outfile == NULL)
    {
      fout = fopen(outfile,"w");
      if (fout == NULL) {fprintf(stderr,"Can't open %s\n", outfile); exit(1);}
    }
  else fout = stdout;

  print_poly(fout, p);
  free_poly(p);

  return 0;
}
#+end_src

** tangle
#+begin_src c :noweb yes :tangle tutte.c
<<includes>>
<<macros>>
<<graphs>>
<<polys>>
<<tarjan>>
<<reductions>>
<<tutte>>
<<main>>
#+end_src


* local lisp variables                                             :noexport:
;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t)
;; End:
